In [0]:
import os
import numpy as np
os.getcwd()
os.chdir("/content/drive/My Drive/Colab Notebooks")
os.getcwd()

'/content/drive/My Drive/Colab Notebooks'

In [0]:
!python prepare_data.py shakespeare_input.txt data

2020-05-23 08:13:48.362592: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
Split input into 22981 sequences...
Serialized 100 sequences...
Serialized 200 sequences...
Serialized 300 sequences...
Serialized 400 sequences...
Serialized 500 sequences...
Serialized 600 sequences...
Serialized 700 sequences...
Serialized 800 sequences...
Serialized 900 sequences...
Serialized 1000 sequences...
Serialized 1100 sequences...
Serialized 1200 sequences...
Serialized 1300 sequences...
Serialized 1400 sequences...
Serialized 1500 sequences...
Serialized 1600 sequences...
Serialized 1700 sequences...
Serialized 1800 sequences...
Serialized 1900 sequences...
Serialized 2000 sequences...
Serialized 2100 sequences...
Serialized 2200 sequences...
Serialized 2300 sequences...
Serialized 2400 sequences...
Serialized 2500 sequences...
Serialized 2600 sequences...
Serialized 2700 sequences...
Serialized 2800 sequences...
Serialized 2900

In [0]:
from prepare_data import parse_seq
import pickle
import tensorflow as tf
%tensorflow_version 2.x

# this is just a datasets of "bytes" (not understandable)
data = tf.data.TFRecordDataset("data.tfrecords")

# this maps a parser function that properly interprets the bytes over the dataset
# (with fixed sequence length 200)
# if you change the sequence length in preprocessing you also need to change it here
data = data.map(lambda x: parse_seq(x, 200))

# a map from characters to indices
vocab = pickle.load(open("data_vocab", mode="rb"))
vocab_size = len(vocab)
# inverse mapping: indices to characters
ind_to_ch = {ind: ch for (ch, ind) in vocab.items()}

print(vocab)
print(vocab_size)

{'P': 1, '&': 2, 'm': 3, "'": 4, 'D': 5, 'q': 6, 'V': 7, 'g': 8, 'J': 9, 'H': 10, 'T': 11, 'A': 12, 'r': 13, 'e': 14, 's': 15, 'b': 16, 'O': 17, '?': 18, 'W': 19, 'j': 20, 'B': 21, 'Q': 22, 'a': 23, 'p': 24, 'i': 25, ',': 26, '\n': 27, 'F': 28, 'X': 29, '-': 30, 'u': 31, 'R': 32, 'I': 33, ';': 34, 't': 35, 'N': 36, 'L': 37, 'E': 38, 'Z': 39, 'v': 40, '[': 41, ']': 42, 'n': 43, 'S': 44, 'w': 45, ' ': 46, '$': 47, 'M': 48, 'x': 49, 'o': 50, 'U': 51, 'K': 52, 'z': 53, 'c': 54, 'k': 55, 'd': 56, 'f': 57, 'y': 58, '.': 59, 'l': 60, 'Y': 61, '!': 62, ':': 63, 'h': 64, 'C': 65, '3': 66, 'G': 67, '<S>': 0}
68


In [0]:
 #to see what is there in my data
for raw_record in data.take(10):        
  print(repr((raw_record)))               

<tf.Tensor: shape=(200,), dtype=int32, numpy=
array([ 0, 28, 25, 13, 15, 35, 46, 65, 25, 35, 25, 53, 14, 43, 63, 27, 21,
       14, 57, 50, 13, 14, 46, 45, 14, 46, 24, 13, 50, 54, 14, 14, 56, 46,
       23, 43, 58, 46, 57, 31, 13, 35, 64, 14, 13, 26, 46, 64, 14, 23, 13,
       46,  3, 14, 46, 15, 24, 14, 23, 55, 59, 27, 27, 12, 60, 60, 63, 27,
       44, 24, 14, 23, 55, 26, 46, 15, 24, 14, 23, 55, 59, 27, 27, 28, 25,
       13, 15, 35, 46, 65, 25, 35, 25, 53, 14, 43, 63, 27, 61, 50, 31, 46,
       23, 13, 14, 46, 23, 60, 60, 46, 13, 14, 15, 50, 60, 40, 14, 56, 46,
       13, 23, 35, 64, 14, 13, 46, 35, 50, 46, 56, 25, 14, 46, 35, 64, 23,
       43, 46, 35, 50, 46, 57, 23,  3, 25, 15, 64, 18, 27, 27, 12, 60, 60,
       63, 27, 32, 14, 15, 50, 60, 40, 14, 56, 59, 46, 13, 14, 15, 50, 60,
       40, 14, 56, 59, 27, 27, 28, 25, 13, 15, 35, 46, 65, 25, 35, 25, 53,
       14, 43, 63, 27, 28, 25, 13, 15, 35, 26, 46, 58, 50], dtype=int32)>
<tf.Tensor: shape=(200,), dtype=int32, numpy=
array([ 0

In [0]:
batch_size = 128
num_epochs = 20

#dataset = data.shuffle(1000+3*batch_size)
dataset = data.padded_batch(batch_size,drop_remainder=True,
                               padded_shapes=([None]))

dataset = dataset.repeat(num_epochs)

In [0]:
 #to see if batches are formed
for raw_record in dataset.take(1):           
  print(repr((raw_record)))
  #print(type(raw_record))
  
   

<tf.Tensor: shape=(128, 200), dtype=int32, numpy=
array([[ 0, 28, 25, ..., 46, 58, 50],
       [ 0, 31, 46, ..., 35, 46, 25],
       [ 0, 35, 46, ..., 60, 56, 46],
       ...,
       [ 0, 50, 35, ..., 27, 27, 48],
       [ 0, 14, 15, ..., 14, 23, 13],
       [ 0, 46, 23, ..., 15,  4, 46]], dtype=int32)>


In [0]:
hidden_layer = 512
n_time_steps = 200

In [0]:
#initial state

#initial = tf.Variable(tf.keras.initializers.GlorotNormal([128,512],minval= -0.1,maxval= 0.1,dtype = np.float32))

#input to hidden weight# weight getting multiplied to input
initializer = tf.keras.initializers.GlorotUniform()

w_xh = tf.Variable(initializer(shape = [vocab_size,hidden_layer]))

#hidden to hidden weight # weight getting multiplied to previous hidden out

w_hh = tf.Variable(initializer(shape= [hidden_layer,hidden_layer]))

#bias which is added after input and hidden matmul
b_hh = tf.Variable(tf.random.uniform([hidden_layer],minval= 0,maxval= 0,dtype = np.float32))

#hidden to output weights#weight multiplied after hidden layer
w_h0 = tf.Variable(initializer(shape=[hidden_layer,vocab_size]))

# bias after intermediate and out weights matmul
b_h0 = tf.Variable(tf.random.uniform([vocab_size],minval= 0,maxval= 0,dtype = np.float32))
variable = [w_xh,w_hh,b_hh,w_h0,b_h0]

In [0]:
print(w_hh)

<tf.Variable 'Variable:0' shape=(512, 512) dtype=float32, numpy=
array([[ 0.0243726 ,  0.04769375, -0.05876251, ...,  0.06525201,
         0.01368494,  0.06082229],
       [ 0.02543978, -0.02505295,  0.02388413, ...,  0.0497435 ,
         0.03363359, -0.00576751],
       [-0.02974753, -0.0521526 , -0.03177339, ..., -0.07195508,
         0.03123108, -0.04529487],
       ...,
       [ 0.0273041 ,  0.0595424 ,  0.01716904, ..., -0.01360125,
        -0.04761079, -0.05492172],
       [ 0.01005622, -0.00114811, -0.04203844, ..., -0.00941188,
         0.04582735,  0.00314347],
       [-0.07446219, -0.02547348,  0.05669775, ...,  0.02754843,
         0.04879282, -0.03557746]], dtype=float32)>


In [0]:
opt = tf.optimizers.Adam()
loss = tf.keras.losses.SparseCategoricalCrossentropy(from_logits= True)
train_acc_metric = tf.keras.metrics.SparseCategoricalAccuracy()
test_acc_metric = tf.keras.metrics.SparseCategoricalAccuracy()

In [0]:
for dat in dataset:
  
  with tf.GradientTape(persistent=True) as tape:
    losser = tf.TensorArray(size = 200,dtype= tf.float32,dynamic_size= True)
    h_t = tf.Variable(tf.random.uniform([batch_size,hidden_layer],minval= 0,maxval= 0,dtype = np.float32))
    for time_step in tf.range(tf.shape(dat)[1]-1):
      
      data = tf.one_hot(dat[:,time_step], vocab_size)
      #print(tf.shape(data))
      # initial = tf.Variable(tf.random.uniform([batch_size,hidden_layer],minval= 0,maxval= 0,dtype = np.float32))
      # if time_step == 0:
      #   a = (tf.matmul(data,w_xh))+ (tf.matmul(initial,w_hh)) + b_hh
      # else:
      a = (tf.matmul(data,w_xh))+ (tf.matmul(h_t, w_hh)) + b_hh
      h_t = tf.nn.tanh(a)
      logits = (tf.matmul(h_t, w_h0)) + b_h0
      logits = tf.convert_to_tensor(logits)
      # print(tf.shape(logits))
      # print(tf.shape(data[:,time_step+1]))

      loss_val = loss(dat[:,time_step+1],logits)
      #print(loss_val)
      losser.write(time_step,value = loss_val).mark_used()
      
  #print(losser.stack()) 
       
    value = tf.math.reduce_mean(losser.stack())
    print((value))  
  
  grads = tape.gradient(value, [w_xh,w_hh,b_hh,w_h0,b_h0]) 
  #print(grads) 
  opt.apply_gradients(zip(grads,[w_xh,w_hh,b_hh,w_h0,b_h0]))






tf.Tensor(4.245239, shape=(), dtype=float32)
tf.Tensor(4.151723, shape=(), dtype=float32)
tf.Tensor(3.8551836, shape=(), dtype=float32)
tf.Tensor(3.6813922, shape=(), dtype=float32)
tf.Tensor(3.456058, shape=(), dtype=float32)
tf.Tensor(3.3761258, shape=(), dtype=float32)
tf.Tensor(3.3857071, shape=(), dtype=float32)
tf.Tensor(3.3425148, shape=(), dtype=float32)
tf.Tensor(3.4053872, shape=(), dtype=float32)
tf.Tensor(3.323594, shape=(), dtype=float32)
tf.Tensor(3.3630466, shape=(), dtype=float32)
tf.Tensor(3.383208, shape=(), dtype=float32)
tf.Tensor(3.269977, shape=(), dtype=float32)
tf.Tensor(3.2574062, shape=(), dtype=float32)
tf.Tensor(3.271204, shape=(), dtype=float32)
tf.Tensor(3.228873, shape=(), dtype=float32)
tf.Tensor(3.2719033, shape=(), dtype=float32)
tf.Tensor(3.2491326, shape=(), dtype=float32)
tf.Tensor(3.2381353, shape=(), dtype=float32)
tf.Tensor(3.2297616, shape=(), dtype=float32)
tf.Tensor(3.224293, shape=(), dtype=float32)
tf.Tensor(3.2188897, shape=(), dtype=float3

In [0]:
num_generate = 10000
from prepare_data import chs_to_inds

# start_char = "A"
# input_eval = chs_to_inds(start_char,vocab)
start = [1,0]

#print(tf.shape(input_eval))


text_generated = []
#temp = 50.0
#h_t = tf.Variable(initializer(shape = [vocab_size,hidden_layer]))

for i in range(num_generate):
  input_eval = tf.one_hot(start[-1:], vocab_size)
  #print(input_eval)
  a = (tf.matmul(input_eval,w_xh))+ (tf.matmul(h_t, w_hh)) + b_hh
  h_t = tf.nn.tanh(a)
  logits = (tf.matmul(h_t, w_h0)) + b_h0
  predictions = tf.nn.softmax(logits)
  
  predictions = predictions.numpy()[0]
  # tf.expand_dims(predictions, 0)
  # print(predictions)
  #predictions = tf.squeeze(predictions, 0)
  #print(predictions)
  #predictions = predictions / temp
  predictions = np.random.choice(vocab_size, p= predictions)
  
  #predictions = tf.random.categorical(predictions, num_samples=1)[0,0].numpy()
  #print(predictions)
  
  #predictions = tf.argmax(predictions) 
  #print(predictions)
  start.append(predictions) 
  start_char = ind_to_ch[predictions]
  text_generated.append(start_char)
  
print(start_char + ''.join(text_generated))


sseur so trip, though he stick my pass hat were he. IN Sil Toby that e, sleep, juigk of strincle,
Pyour sobe but thou be there good defica.

CALUWIS:
Be augh to sphan like a father.

JUSIO:
Is not the peecrifes ears, as apperous too a word.

VAMENN FURDINAH: I as ceps, this in this door that should to
Blintern some winds low fall you think?
I love thee our honger awaigh, a'l on the dese, for I'll walke how some after and cange Cleawn,
No, me hereing reach wal grase. Mownce, madvalterure I stee speak,
This placond, soor huly lot's just carry but the sade that comme to
this cay.

BERVILIO:
Be hath no 'Imad me to thee with me;
that a witter princes, was have I not faw younce.
OS: I smoll should reasons to hith propage.

QUEEN MA PRICHU
D
OMARIO:
No maitial in my scous oversiop of this away;
But sweet reast and trous, you have been buck is not know hear' the prosent. you, this hed; as he is a speak of scarcess.

PAgh:
In wost defore ye'll recold should be talones the miads aid that is word

In [0]:
num_generate = 10000
#from prepare_data import chs_to_inds

#start_char = '<S>'
#input_eval = chs_to_inds(start_char,vocab)
#print(input_eval)
#input_eval = tf.one_hot(input_eval, vocab_size)
#print(input_eval)

text_generated = []
#temp = 1.5
#h_t = tf.zeros([batch_size,hidden_layer])
choice = [0]
#print(tf.shape(h_t))

for i in range(num_generate):
  x_t = tf.one_hot(choice[-1:],depth = vocab_size)
  #print(tf.shape(x_t))
  a = (tf.matmul(x_t,w_xh))+ (tf.matmul(h_t, w_hh)) + b_hh
  #print(type(a))
  h_t = tf.nn.tanh(a)
  logits = (tf.matmul(h_t, w_h0)) + b_h0
  #print(logits)
  predictions = tf.nn.softmax(logits)
  #print(tf.shape(predictions))
  #predictions = predictions[0,:]
  # predictions = tf.squeeze(predictions, 0)
  ##print(predictions.shape)
  #predictions = predictions / temp
  predictions = predictions.numpy()[0]
  #print(predictions)
  char_choice = np.random.choice(vocab_size, p = predictions)
  choice.append(char_choice)
  #predictions = tf.random.categorical(predictions, num_samples=1)[-1,0].numpy()
  #print(predictions)
  start_char = ind_to_ch[char_choice]
  #print(input_eval)
  text_generated.append(start_char)
  
print(start_char + ''.join(text_generated))

gons! No morey adlanse of G dome to
The alftar and my skeept.
Unou'linger it, solds him,
dissest expenityour prothen me, some noir was I'll? I dene, are this honseen my sontlest; Alentwell, blean far I see the wing a brebaro.
Bolt, mer, in thy coveninal, his
Yor gartle a love Bistarched master.

GRATIA:
Give your brought is one piby die
Enitwere of nobiectl be appires
You well seek wom'

LADD MACBETH:
Dich to more thou dlow'd the peece of herleing,
O, holk a
Aelse it, for a sailse-means how
we come by; I still
Ho that wer tell you have sees no seem to our proadst bid Pome, or serve the rudlat some ho
Wit out o'ervincus
By three nordes spees but a
ANred of them me in years!

GIO NOLET:
Mused in show to hust I can in prodick you to oppiser mousty
As no cous not the princely pownet--bound thee
And stase will a speak mad, up this means Masser, that hang dream no mouth be not muss
That I do so smoway, love
And Salictly heavy course.

SURIO:

AGRIAPHIR:
Sir both when creasure not thmouth'd f